package org.bullet

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class HardestSudokuTest {

    @Test
    fun testCorrectMovesGenerated() {
        val sudokuSolver = SudokuSolver(HardestSudoku())

        val moves = sudokuSolver.solve().sortedBy { it.cell.id }

        assertEquals(8, moves[0].value)
        assertEquals(1, moves[1].value)
        assertEquals(2, moves[2].value)
        assertEquals(7, moves[3].value)
        assertEquals(5, moves[4].value)
        assertEquals(3, moves[5].value)
        assertEquals(6, moves[6].value)
        assertEquals(4, moves[7].value)
        assertEquals(9, moves[8].value)
        assertEquals(9, moves[9].value)
        assertEquals(4, moves[10].value)
        assertEquals(3, moves[11].value)
        assertEquals(6, moves[12].value)
        assertEquals(8, moves[13].value)
        assertEquals(2, moves[14].value)
        assertEquals(1, moves[15].value)
        assertEquals(7, moves[16].value)
        assertEquals(5, moves[17].value)
        assertEquals(6, moves[18].value)
        assertEquals(7, moves[19].value)
        assertEquals(5, moves[20].value)
        assertEquals(4, moves[21].value)
        assertEquals(9, moves[22].value)
        assertEquals(1, moves[23].value)
        assertEquals(2, moves[24].value)
        assertEquals(8, moves[25].value)
        assertEquals(3, moves[26].value)
        assertEquals(1, moves[27].value)
        assertEquals(5, moves[28].value)
        assertEquals(4, moves[29].value)
        assertEquals(2, moves[30].value)
        assertEquals(3, moves[31].value)
        assertEquals(7, moves[32].value)
        assertEquals(8, moves[33].value)
        assertEquals(9, moves[34].value)
        assertEquals(6, moves[35].value)
        assertEquals(3, moves[36].value)
        assertEquals(6, moves[37].value)
        assertEquals(9, moves[38].value)
        assertEquals(8, moves[39].value)
        assertEquals(4, moves[40].value)
        assertEquals(5, moves[41].value)
        assertEquals(7, moves[42].value)
        assertEquals(2, moves[43].value)
        assertEquals(1, moves[44].value)
        assertEquals(2, moves[45].value)
        assertEquals(8, moves[46].value)
        assertEquals(7, moves[47].value)
        assertEquals(1, moves[48].value)
        assertEquals(6, moves[49].value)
        assertEquals(9, moves[50].value)
        assertEquals(5, moves[51].value)
        assertEquals(3, moves[52].value)
        assertEquals(4, moves[53].value)
        assertEquals(5, moves[54].value)
        assertEquals(2, moves[55].value)
        assertEquals(1, moves[56].value)
        assertEquals(9, moves[57].value)
        assertEquals(7, moves[58].value)
        assertEquals(4, moves[59].value)
        assertEquals(3, moves[60].value)
        assertEquals(6, moves[61].value)
        assertEquals(8, moves[62].value)
        assertEquals(4, moves[63].value)
        assertEquals(3, moves[64].value)
        assertEquals(8, moves[65].value)
        assertEquals(5, moves[66].value)
        assertEquals(2, moves[67].value)
        assertEquals(6, moves[68].value)
        assertEquals(9, moves[69].value)
        assertEquals(1, moves[70].value)
        assertEquals(7, moves[71].value)
        assertEquals(7, moves[72].value)
        assertEquals(9, moves[73].value)
        assertEquals(6, moves[74].value)
        assertEquals(3, moves[75].value)
        assertEquals(1, moves[76].value)
        assertEquals(8, moves[77].value)
        assertEquals(4, moves[78].value)
        assertEquals(5, moves[79].value)
        assertEquals(2, moves[80].value)
    }
}
